---
services:
  traefik:
    configs:
      - source: auth_toml
        target: /etc/traefik/dynamic/auth.toml
        uid: "0"
        gid: "0"
        # trunk-ignore(yamllint/octal-values)
        mode: 0440
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

configs:
  traefik_toml:
    file: config/core.home.molier.net/traefik.toml
  auth_toml:
    file: config/core.home.molier.net/auth.toml
