---
services:
  traefik:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

configs:
  traefik_toml:
    file: config/core.home.molier.net/traefik.toml
