################################################################
# Global configuration
################################################################
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

################################################################
# Entrypoints configuration
################################################################
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

################################################################
# Traefik logs configuration
################################################################
[log]
  # level = "DEBUG"

################################################################
# Access logs configuration
################################################################
[accessLog]

################################################################
# API and dashboard configuration
################################################################
[api]

  # insecure = true
  # dashboard = false

################################################################
# Ping configuration
################################################################
[ping]
  # entryPoint = "traefik"


[providers]
  ################################################################
  # Dynamic file configuration backend
  ################################################################
  [providers.file]
    directory = "/etc/traefik/dynamic"
    watch = true
    
  ################################################################
  # Docker configuration backend
  ################################################################
  [providers.docker]
    watch = true
    exposedByDefault = false
    network = "ingress_network"

################################################################
# Step-CA ACME configuration
################################################################
[certificatesResolvers.step-ca.acme]
  email = "hostmaster@home.molier.net"
  storage = "/etc/traefik/acme/step-ca.json"
  caServer = "https://ca.home.molier.net/acme/acme/directory"
  [certificatesResolvers.step-ca.acme.httpChallenge]
    entryPoint = "web"
  [certificatesResolvers.step-ca.acme.tlsChallenge]

    